from app.llm.prompts.industry import INDUSTRY_SYSTEM_PROMPT, INDUSTRY_USER_TEMPLATE
from app.llm.prompts.financial_quality import FINANCIAL_QUALITY_SYSTEM_PROMPT, FINANCIAL_QUALITY_USER_TEMPLATE
from app.llm.prompts.moat import MOAT_SYSTEM_PROMPT, MOAT_USER_TEMPLATE
from app.llm.prompts.valuation import VALUATION_SYSTEM_PROMPT, VALUATION_USER_TEMPLATE
from app.llm.prompts.risk import RISK_SYSTEM_PROMPT, RISK_USER_TEMPLATE
from app.llm.prompts.thesis import THESIS_SYSTEM_PROMPT, THESIS_USER_TEMPLATE
from app.llm.prompts.business_model import BUSINESS_MODEL_SYSTEM_PROMPT, BUSINESS_MODEL_USER_TEMPLATE
from app.llm.prompts.management import MANAGEMENT_SYSTEM_PROMPT, MANAGEMENT_USER_TEMPLATE
from app.llm.prompts.monitoring import MONITORING_SYSTEM_PROMPT, MONITORING_USER_TEMPLATE

__all__ = [
    "INDUSTRY_SYSTEM_PROMPT", "INDUSTRY_USER_TEMPLATE",
    "FINANCIAL_QUALITY_SYSTEM_PROMPT", "FINANCIAL_QUALITY_USER_TEMPLATE",
    "MOAT_SYSTEM_PROMPT", "MOAT_USER_TEMPLATE",
    "VALUATION_SYSTEM_PROMPT", "VALUATION_USER_TEMPLATE",
    "RISK_SYSTEM_PROMPT", "RISK_USER_TEMPLATE",
    "THESIS_SYSTEM_PROMPT", "THESIS_USER_TEMPLATE",
    "BUSINESS_MODEL_SYSTEM_PROMPT", "BUSINESS_MODEL_USER_TEMPLATE",
    "MANAGEMENT_SYSTEM_PROMPT", "MANAGEMENT_USER_TEMPLATE",
    "MONITORING_SYSTEM_PROMPT", "MONITORING_USER_TEMPLATE",
]
